### ISSUE TITLE
pods folder missing

### ISSUE THREAD

**Issue by wellkunnected** [classmere/app#21]
Hi,

I want to test this app but after running pod install it's giving me the error that the "pods folder is missing" Can you add it to the repo please?

**Comment by brandonlee503** [comment]
Hey man,

So I tried replicating your error, but when I simply do a fresh git clone and pod install, it seems to work just fine. Do you have CocoaPods installed?

**Comment by wellkunnected** [comment]
Yes I do but it never works for me unless there's a pods folder included with the project :(
  
  
 Download   Email (https://itunes.apple.com/app/apple-store/id922793622?pt=814382&mt=8&ct=download_email)
  
  
  
  

  
  
>

**Comment by wellkunnected** [comment]
Can you include the pods folder?

**Comment by rutgerfarry** [comment]
@wellkunnected Running `pod install` should create the Pods folder. I'd ensure your [Cocoapods](https://cocoapods.org) installation is up to date
