### ISSUE TITLE
Polish Code

### ISSUE THREAD

**Issue by brandonlee503** [classmere/app#8]
Make the code look better with some better practices such as:
https://github.com/futurice/ios-good-practices
https://github.com/codepath/ios_guides/wiki/Swift-Intermediate

**Comment by brandonlee503** [comment]
https://github.com/github/swift-style-guide

**Comment by rutgerfarry** [comment]
https://github.com/schwa/Swift-Community-Best-Practices/

**Comment by rutgerfarry** [comment]
Also we should implement MVVM throughout the parts of the app that were copied over. Here's some resources:
https://www.objc.io/issues/13-architecture/mvvm/
https://en.wikipedia.org/wiki/Model_View_ViewModel
https://realm.io/news/andy-matuschak-refactor-mega-controller/

**Comment by brandonlee503** [comment]
Cleaned up a bit.
